### ISSUE TITLE
Wrong SUITE for mips64el 

### ISSUE THREAD

**Issue by ydcool** [multiarch/debian-debootstrap#17]
Thanks to this PR add support for mips64el, but that seems made a mistake for SUITE , is it all right ?  @illuspas

https://github.com/multiarch/debian-debootstrap/pull/16

https://github.com/multiarch/debian-debootstrap/blob/4c34f3222010692d3062b0b79c0d5c97c774362b/.travis.yml#L34

https://github.com/multiarch/debian-debootstrap/blob/4c34f3222010692d3062b0b79c0d5c97c774362b/.travis.yml#L44

https://github.com/multiarch/debian-debootstrap/blob/4c34f3222010692d3062b0b79c0d5c97c774362b/.travis.yml#L54

**Comment by lafin** [comment]
good catch. thank you :)
