### ISSUE TITLE
Missing tags

### ISSUE THREAD

**Issue by landswellsong** [multiarch/debian-debootstrap#2]
There is a folder for `mips-jessie` (also `ppc64el-jessie`), but there is no relevant tag on docker hub, is that intentional or am I doing something wrong?

PS: Thanks for this wonderful package, it is awesome

**Comment by moul** [comment]
Hi Oleksiy,

I had some build errors the I tried to build this tag.
It may come from qemu compatibility or from the debootstrap ecosystem; we definitely need to give a new try

I will give a look soon, if you want to try by yourself, you need an intel machine with docker

Manfred

**Comment by landswellsong** [comment]
Thank you for your response. I guess I will try on my own soon and return with findings here.

**Comment by landswellsong** [comment]
Hi, @moul 
I tried building the images and it seemed to work on my Ubuntu machine (tried `jessie-mips` and `jessie-mipsel`). I wonder if you could give it a new try and in case of errors tell which ones are there exactly for I don't seem to be able to reproduce.

**Comment by moul** [comment]
yep, sure

trying again right now

**Comment by moul** [comment]
I can confirm, thanks!

I'm currently pushing the images

**Comment by moul** [comment]
Should be ok, can you recheck ?

**Comment by landswellsong** [comment]
Whoah, thank you very much! I'm enabling in my build and will respond in the morning with the findings if it works.

**Comment by landswellsong** [comment]
Okay, it doesn't seem to work. Both travis and my local setup all have the same error that they can't find `bash`. Somehow `qemu` doesn't pick up, but if you invoke it manually it works nice. I'll be investigating further and report back. Sorry for the ado.

**Comment by moul** [comment]
Ok, if you have more details to share, I can try to find a workaround. Good luck

**Comment by landswellsong** [comment]
@meyskens is it fixed or not applicable anymore?

**Comment by meyskens** [comment]
@landwellsong with the new way of building this should be fixed. If not please let us know so we can take a 2nd look

**Comment by landswellsong** [comment]
@meyskens great news, thank you. I'll update my travis scripts and see how it fares.
