### ISSUE TITLE
deprecated ? yes : no

### ISSUE THREAD

**Issue by bebehei** [multiarch/debian-debootstrap#5]
@meyskens As you stated in multiarch/ubuntu-debootstrap#14 ubuntu-deboostrap is deprecated.

But what about this repository? Is this repository deprecated, too?

**Comment by meyskens** [comment]
Probably not, i forked this one and it works fine. Ubuntu has 2 repos Debian only this one

**Comment by bebehei** [comment]
> Probably not, i forked this one and it works fine. Ubuntu has 2 repos Debian only this one

Ah, ok. So I interpret this as "Pull requests Welcome". 😁 

Can someone explain me, how these images get built and uploaded to docker hub? Unfortunately, travis-ci is not successful in this repository.

**Comment by meyskens** [comment]
https://github.com/meyskens/debian-debootstrap/blob/master/.travis.yml

It doesn't work on Travis as it needs a patch on QEMU that is only in Xenial/Jessie.
